export const ROUTES = {
	HOME: "/",
	SERVIECS: "/services",
	CASES: "/cases",
	AI: "/ai",
	ABOUT_US: "/about-us",
	CONTACT_US: "/contact-us",
	AI_STRATEGY: "/ai-strategy",
	TEAM: "/team",
	AUTOMATION: "/automation",
	POST: "/post",
	PRIVACY: "/privacy",
	TERMS: "/terms",
	CASE_POKER_BRAIN: "/cases#poker-brain",
	CASE_AI_AUTOMATION: "/cases#ai-automation",
	CASE_DEVELOPMENT_AUTOMATION: "/cases#development-automation",
	CASE_SOCIAL_MEDIA: "/cases#social-media",
} as const
